# cohort name
cohort_name: 'test1'

# directories
main_dir: '{your_work_dir}'
py27_dir: '{your_work_dir}/mambaforge/envs/py27/bin/python'
py39_dir: '{your_work_dir}/mambaforge/envs/py39/bin/python'
# reference_dir:
# software_dir:
# database_dir:

# files
parliment_docker: 'docker.io/dnanexus/parliament2:latest'
chromoseq_docker: 'docker.io/zatawada/docker-basespace_chromoseq_v2:master'
sample_list: '{your_work_dir}/sample_list'
sample: 'Sample_1'
gender: 'Male'

# sv settings
parliment2_sv_callers: ['breakdancer','cnvnator','delly.deletion','delly.duplication','delly.inversion']
chromoseq_sv_callers: ['ichnorcnv','manta']
size: 10000
kfolds_shuffle: 5
