# cohort name
cohort_name: '{your_cohort_name}'

# directories
main_dir: '{your_work_dir}'
cyto_sv_ml_dir: '{cyto_sv_ml_dir}'
py27_dir: '{your_work_dir}/miniconda3/envs/py27/bin'
py39_dir: '{your_work_dir}/miniconda3/envs/py39/bin'

# reference_dir:
# software_dir:
# database_dir:

# files
parliament_docker: 'docker.io/dnanexus/parliament2:latest'
chromoseq_docker: 'docker.io/zatawada/docker-basespace_chromoseq_v2:master'
sample_list: '{your_work_dir}/{sample_list}'
sample: '{Sample_1}'
gender: '{Male}'
cyto_band_file: '{cyto_sv_ml_dir}/cyto_band_dict.csv'
sv_feature_metrics_index_file: '{cyto_sv_ml_dir}/sv_feature_metrics.csv'

# sv settings
# SV caller list
parliament2_sv_callers: ['breakdancer','cnvnator','delly.deletion','delly.duplication','delly.inversion']
chromoseq_sv_callers: ['ichnorcnv','manta']
# SV database list
sv_db: ['1000_g', '1000_gall', 'cosmic_s', 'cytoatlas_s', 'gnomad_g2ab', 'gnomad_gall', 'gnomad_g', 'gnomad_qc', 'centromere_qc', 'dgv_g', 'control_g', 'control_gall']
# 'size': SV size < 10000 bp will be excluded in the analyses; 
size: 10000
# 'trs_sv_cutoff': SV breakpoint distance > 1000 bp to SVs in database annotation will be not be labelled;  'nontrs_sv_cutoff': SV region overlap < 0.9 (90%) to SVs in database annotation will be not be labelled;
trs_sv_cutoff: 1000
nontrs_sv_cutoff : 0.9
# kfolds: k folds for machine learning models
kfolds: 5
