# cohort name
cohort_name: 'test'

# directories
main_dir: '/home/tzhang'
py27_dir: '/home/tzhang/mambaforge/envs/py27/bin/python'
# reference_dir:
# software_dir:
# database_dir:

# files
parliment_docker: 'docker.io/dnanexus/parliament2:latest'
chromoseq_docker: 'docker.io/zatawada/docker-basespace_chromoseq_v2:master'
sample_list: '/home/tzhang/sample'
sample: 'MDS_patient1'

# sv settings
parliment2_sv_callers: ['breakdancer','cnvnator','delly.deletion','delly.duplication','delly.inversion']
chromoseq_sv_callers: ['ichnorcnv','manta']
size: 10000
