# cohort name
cohort_name: '{your_cohort_name}'

# directories
main_dir: '{your_work_dir}'
cyto_sv_ml_dir: '{cyto_sv_ml_dir}'
py27_dir: '{your_work_dir}/miniconda3/envs/py27/bin'
py39_dir: '{your_work_dir}/miniconda3/envs/py39/bin'

# reference_dir:
# software_dir:
# database_dir:

# files
parliment_docker: 'docker.io/dnanexus/parliament2:latest'
chromoseq_docker: 'docker.io/zatawada/docker-basespace_chromoseq_v2:master'
sample_list: '{your_work_dir}/{sample_list}'
sample: '{Sample_1}'
gender: '{Male}'
cyto_band_file: '{cyto_sv_ml_dir}/cyto_band_dict.csv'

# sv settings
parliment2_sv_callers: ['breakdancer','cnvnator','delly.deletion','delly.duplication','delly.inversion']
chromoseq_sv_callers: ['ichnorcnv','manta']
sv_db: ['1000_g', '1000_gall', 'cosmic_s', 'cytoatlas_s', 'gnomad_g2ab', 'gnomad_gall', 'gnomad_g', 'gnomad_qc', 'centromere_qc', 'dgv_g', 'control_g', 'control_gall']
size: 10000
kfolds_shuffle: 5
